[2024-06-19 13:13:28,009] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T13:13:26.281084+00:00 [queued]>
[2024-06-19 13:13:28,023] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T13:13:26.281084+00:00 [queued]>
[2024-06-19 13:13:28,023] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 13:13:28,024] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-06-19 13:13:28,024] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 13:13:28,042] {taskinstance.py:1397} INFO - Executing <Task(PostgresFileOperator): Insertar_Data> on 2024-06-19 13:13:26.281084+00:00
[2024-06-19 13:13:28,048] {standard_task_runner.py:52} INFO - Started process 474 to run task
[2024-06-19 13:13:28,052] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tecnica_postgres', 'Insertar_Data', 'manual__2024-06-19T13:13:26.281084+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/tecnica_posgres.py', '--cfg-path', '/var/tmp/tmpftlg51ut', '--error-file', '/var/tmp/tmpphz71w1a']
[2024-06-19 13:13:28,053] {standard_task_runner.py:80} INFO - Job 25: Subtask Insertar_Data
[2024-06-19 13:13:28,147] {task_command.py:371} INFO - Running <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T13:13:26.281084+00:00 [running]> on host 8328f391602b
[2024-06-19 13:13:28,316] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tecnica_postgres
AIRFLOW_CTX_TASK_ID=Insertar_Data
AIRFLOW_CTX_EXECUTION_DATE=2024-06-19T13:13:26.281084+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-19T13:13:26.281084+00:00
[2024-06-19 13:13:28,317] {postgres.py:127} INFO - Running copy expert: COPY tecnica_ml FROM STDIN, filename: /opt/***/data/file.csv
[2024-06-19 13:13:28,361] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-19 13:13:28,411] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/PostgresFileOperator.py", line 22, in execute
    self.writeInDb()
  File "/opt/airflow/plugins/operators/PostgresFileOperator.py", line 27, in writeInDb
    self.postgres_hook.bulk_load(self.config.get("table_name"), "/opt/airflow/data/file.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 149, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 135, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(100)
CONTEXT:  COPY tecnica_ml, line 1, column id: "MLA1500807986,Horno Microondas Con Grill LG - 42 Litros Mh8298dir,399999,http://http2.mlstatic.com/D..."

[2024-06-19 13:13:28,437] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=tecnica_postgres, task_id=Insertar_Data, execution_date=20240619T131326, start_date=20240619T131328, end_date=20240619T131328
[2024-06-19 13:13:28,660] {standard_task_runner.py:97} ERROR - Failed to execute job 25 for task Insertar_Data (value too long for type character varying(100)
CONTEXT:  COPY tecnica_ml, line 1, column id: "MLA1500807986,Horno Microondas Con Grill LG - 42 Litros Mh8298dir,399999,http://http2.mlstatic.com/D..."
; 474)
[2024-06-19 13:13:28,705] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-06-19 13:13:28,752] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
