[2024-06-19 13:25:25,836] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T13:20:22.978206+00:00 [queued]>
[2024-06-19 13:25:25,849] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T13:20:22.978206+00:00 [queued]>
[2024-06-19 13:25:25,850] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 13:25:25,850] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2024-06-19 13:25:25,851] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 13:25:25,870] {taskinstance.py:1397} INFO - Executing <Task(PostgresFileOperator): Insertar_Data> on 2024-06-19 13:20:22.978206+00:00
[2024-06-19 13:25:25,875] {standard_task_runner.py:52} INFO - Started process 359 to run task
[2024-06-19 13:25:25,878] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tecnica_postgres', 'Insertar_Data', 'manual__2024-06-19T13:20:22.978206+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/tecnica_posgres.py', '--cfg-path', '/var/tmp/tmpt47tj3f1', '--error-file', '/var/tmp/tmp85i_2zzn']
[2024-06-19 13:25:25,879] {standard_task_runner.py:80} INFO - Job 32: Subtask Insertar_Data
[2024-06-19 13:25:25,950] {task_command.py:371} INFO - Running <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T13:20:22.978206+00:00 [running]> on host 284150aff6b6
[2024-06-19 13:25:26,034] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tecnica_postgres
AIRFLOW_CTX_TASK_ID=Insertar_Data
AIRFLOW_CTX_EXECUTION_DATE=2024-06-19T13:20:22.978206+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-19T13:20:22.978206+00:00
[2024-06-19 13:25:26,035] {postgres.py:127} INFO - Running copy expert: COPY tecnica_ml FROM STDIN, filename: /opt/***/data/file.csv
[2024-06-19 13:25:26,038] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/PostgresFileOperator.py", line 22, in execute
    self.writeInDb()
  File "/opt/airflow/plugins/operators/PostgresFileOperator.py", line 27, in writeInDb
    self.postgres_hook.bulk_load(self.config.get("table_name"), "/opt/airflow/data/file.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 149, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 132, in copy_expert
    with open(filename, 'r+') as file:
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/file.csv'
[2024-06-19 13:25:26,052] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=tecnica_postgres, task_id=Insertar_Data, execution_date=20240619T132022, start_date=20240619T132525, end_date=20240619T132526
[2024-06-19 13:25:26,073] {standard_task_runner.py:97} ERROR - Failed to execute job 32 for task Insertar_Data ([Errno 13] Permission denied: '/opt/airflow/data/file.csv'; 359)
[2024-06-19 13:25:26,090] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-06-19 13:25:26,131] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
