[2024-06-19 02:33:06,729] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Crear_tabla manual__2024-06-19T02:33:04.378535+00:00 [queued]>
[2024-06-19 02:33:06,742] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Crear_tabla manual__2024-06-19T02:33:04.378535+00:00 [queued]>
[2024-06-19 02:33:06,742] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 02:33:06,743] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-06-19 02:33:06,743] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 02:33:06,763] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): Crear_tabla> on 2024-06-19 02:33:04.378535+00:00
[2024-06-19 02:33:06,770] {standard_task_runner.py:52} INFO - Started process 794 to run task
[2024-06-19 02:33:06,784] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tecnica_postgres', 'Crear_tabla', 'manual__2024-06-19T02:33:04.378535+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/tecnica_posgres.py', '--cfg-path', '/var/tmp/tmpa8ixvadb', '--error-file', '/var/tmp/tmp6_jfyimn']
[2024-06-19 02:33:06,791] {standard_task_runner.py:80} INFO - Job 2: Subtask Crear_tabla
[2024-06-19 02:33:07,102] {task_command.py:371} INFO - Running <TaskInstance: tecnica_postgres.Crear_tabla manual__2024-06-19T02:33:04.378535+00:00 [running]> on host f8e18ce51c9d
[2024-06-19 02:33:07,256] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tecnica_postgres
AIRFLOW_CTX_TASK_ID=Crear_tabla
AIRFLOW_CTX_EXECUTION_DATE=2024-06-19T02:33:04.378535+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-19T02:33:04.378535+00:00
[2024-06-19 02:33:07,286] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 204, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2024-06-19 02:33:07,317] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=tecnica_postgres, task_id=Crear_tabla, execution_date=20240619T023304, start_date=20240619T023306, end_date=20240619T023307
[2024-06-19 02:33:07,344] {standard_task_runner.py:97} ERROR - Failed to execute job 2 for task Crear_tabla (The conn_id `postgres_localhost` isn't defined; 794)
[2024-06-19 02:33:07,399] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-06-19 02:33:07,444] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
