[2024-06-19 13:30:17,623] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T13:30:15.061796+00:00 [queued]>
[2024-06-19 13:30:17,636] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T13:30:15.061796+00:00 [queued]>
[2024-06-19 13:30:17,637] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 13:30:17,637] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-06-19 13:30:17,638] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 13:30:17,658] {taskinstance.py:1397} INFO - Executing <Task(PostgresFileOperator): Insertar_Data> on 2024-06-19 13:30:15.061796+00:00
[2024-06-19 13:30:17,662] {standard_task_runner.py:52} INFO - Started process 510 to run task
[2024-06-19 13:30:17,665] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tecnica_postgres', 'Insertar_Data', 'manual__2024-06-19T13:30:15.061796+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/tecnica_posgres.py', '--cfg-path', '/var/tmp/tmp6l786h7k', '--error-file', '/var/tmp/tmp0j71ro2r']
[2024-06-19 13:30:17,667] {standard_task_runner.py:80} INFO - Job 35: Subtask Insertar_Data
[2024-06-19 13:30:17,768] {task_command.py:371} INFO - Running <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T13:30:15.061796+00:00 [running]> on host 284150aff6b6
[2024-06-19 13:30:17,876] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tecnica_postgres
AIRFLOW_CTX_TASK_ID=Insertar_Data
AIRFLOW_CTX_EXECUTION_DATE=2024-06-19T13:30:15.061796+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-19T13:30:15.061796+00:00
[2024-06-19 13:30:17,877] {postgres.py:127} INFO - Running copy expert: COPY tecnica_ml FROM STDIN, filename: /opt/***/data/file.csv
[2024-06-19 13:30:17,880] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/PostgresFileOperator.py", line 22, in execute
    self.writeInDb()
  File "/opt/airflow/plugins/operators/PostgresFileOperator.py", line 27, in writeInDb
    self.postgres_hook.bulk_load(self.config.get("table_name"), "/opt/airflow/data/file.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 149, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 132, in copy_expert
    with open(filename, 'r+') as file:
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/file.csv'
[2024-06-19 13:30:17,921] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=tecnica_postgres, task_id=Insertar_Data, execution_date=20240619T133015, start_date=20240619T133017, end_date=20240619T133017
[2024-06-19 13:30:17,944] {standard_task_runner.py:97} ERROR - Failed to execute job 35 for task Insertar_Data ([Errno 13] Permission denied: '/opt/airflow/data/file.csv'; 510)
[2024-06-19 13:30:17,958] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-06-19 13:30:18,007] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
