[2024-06-19 03:53:07,861] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T03:53:05.454104+00:00 [queued]>
[2024-06-19 03:53:07,873] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T03:53:05.454104+00:00 [queued]>
[2024-06-19 03:53:07,874] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 03:53:07,874] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-06-19 03:53:07,875] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 03:53:07,891] {taskinstance.py:1397} INFO - Executing <Task(PostgresFileOperator): Insertar_Data> on 2024-06-19 03:53:05.454104+00:00
[2024-06-19 03:53:07,896] {standard_task_runner.py:52} INFO - Started process 291 to run task
[2024-06-19 03:53:07,899] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tecnica_postgres', 'Insertar_Data', 'manual__2024-06-19T03:53:05.454104+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tecnica_posgres.py', '--cfg-path', '/var/tmp/tmp9wyqrn66', '--error-file', '/var/tmp/tmp4mtcr3dg']
[2024-06-19 03:53:07,901] {standard_task_runner.py:80} INFO - Job 10: Subtask Insertar_Data
[2024-06-19 03:53:07,978] {task_command.py:371} INFO - Running <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T03:53:05.454104+00:00 [running]> on host c165e7139fa2
[2024-06-19 03:53:08,083] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tecnica_postgres
AIRFLOW_CTX_TASK_ID=Insertar_Data
AIRFLOW_CTX_EXECUTION_DATE=2024-06-19T03:53:05.454104+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-19T03:53:05.454104+00:00
[2024-06-19 03:53:08,084] {postgres.py:127} INFO - Running copy expert: COPY tecnica_ml FROM STDIN, filename: /opt/***/data/file.csv
[2024-06-19 03:53:08,102] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-19 03:53:08,134] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/PostgresFileOperator.py", line 22, in execute
    self.writeInDb()
  File "/opt/airflow/plugins/operators/PostgresFileOperator.py", line 27, in writeInDb
    self.postgres_hook.bulk_load(self.config.get("table_name"), "/opt/airflow/data/file.csv")  # Cambia la ruta
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 149, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 135, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: missing data for column "title"
CONTEXT:  COPY tecnica_ml, line 1: "ID,Title,Price,Sold Quantity,Thumbnail,Date"

[2024-06-19 03:53:08,151] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=tecnica_postgres, task_id=Insertar_Data, execution_date=20240619T035305, start_date=20240619T035307, end_date=20240619T035308
[2024-06-19 03:53:08,359] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task Insertar_Data (missing data for column "title"
CONTEXT:  COPY tecnica_ml, line 1: "ID,Title,Price,Sold Quantity,Thumbnail,Date"
; 291)
[2024-06-19 03:53:08,392] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-06-19 03:53:08,545] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
