[2024-06-19 13:29:56,016] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T13:24:53.340542+00:00 [queued]>
[2024-06-19 13:29:56,029] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T13:24:53.340542+00:00 [queued]>
[2024-06-19 13:29:56,030] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 13:29:56,030] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2024-06-19 13:29:56,030] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-19 13:29:56,052] {taskinstance.py:1397} INFO - Executing <Task(PostgresFileOperator): Insertar_Data> on 2024-06-19 13:24:53.340542+00:00
[2024-06-19 13:29:56,057] {standard_task_runner.py:52} INFO - Started process 491 to run task
[2024-06-19 13:29:56,060] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tecnica_postgres', 'Insertar_Data', 'manual__2024-06-19T13:24:53.340542+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/tecnica_posgres.py', '--cfg-path', '/var/tmp/tmpr44285fb', '--error-file', '/var/tmp/tmp92_1to6u']
[2024-06-19 13:29:56,061] {standard_task_runner.py:80} INFO - Job 33: Subtask Insertar_Data
[2024-06-19 13:29:56,143] {task_command.py:371} INFO - Running <TaskInstance: tecnica_postgres.Insertar_Data manual__2024-06-19T13:24:53.340542+00:00 [running]> on host 284150aff6b6
[2024-06-19 13:29:56,236] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tecnica_postgres
AIRFLOW_CTX_TASK_ID=Insertar_Data
AIRFLOW_CTX_EXECUTION_DATE=2024-06-19T13:24:53.340542+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-19T13:24:53.340542+00:00
[2024-06-19 13:29:56,237] {postgres.py:127} INFO - Running copy expert: COPY tecnica_ml FROM STDIN, filename: /opt/***/data/file.csv
[2024-06-19 13:29:56,239] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/PostgresFileOperator.py", line 22, in execute
    self.writeInDb()
  File "/opt/airflow/plugins/operators/PostgresFileOperator.py", line 27, in writeInDb
    self.postgres_hook.bulk_load(self.config.get("table_name"), "/opt/airflow/data/file.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 149, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 132, in copy_expert
    with open(filename, 'r+') as file:
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/file.csv'
[2024-06-19 13:29:56,253] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=tecnica_postgres, task_id=Insertar_Data, execution_date=20240619T132453, start_date=20240619T132956, end_date=20240619T132956
[2024-06-19 13:29:56,271] {standard_task_runner.py:97} ERROR - Failed to execute job 33 for task Insertar_Data ([Errno 13] Permission denied: '/opt/airflow/data/file.csv'; 491)
[2024-06-19 13:29:56,312] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-06-19 13:29:56,353] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
